apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: mysql
  labels:
    app: mysql
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
